### ISSUE TITLE
On_message_delete throws KeyError

### ISSUE THREAD

**Issue by RillJ** [Gitfoe/ChadCounting#13]
During runtime, very regularly, an error is thrown within the on_mesage_delete method.
```[2024-03-12 20:38:51] [ERROR   ] discord.client: Ignoring exception in on_message_delete
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/ChadCounting/bot.py", line 103, in on_message_delete
    current_user_minutes_ban = check_user_banned(user_id, guild_id)
  File "/ChadCounting/bot.py", line 491, in check_user_banned
    user_time_banned = guild_data[guild_id]["users"][user_id]["time_banned"]
KeyError: 1115440368331272233
[2024-03-12 20:39:02] [ERROR   ] discord.client: Ignoring exception in on_message_delete
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/ChadCounting/bot.py", line 103, in on_message_delete
    current_user_minutes_ban = check_user_banned(user_id, guild_id)
  File "/ChadCounting/bot.py", line 491, in check_user_banned
    user_time_banned = guild_data[guild_id]["users"][user_id]["time_banned"]
KeyError: 538417546303373342```

**Comment by DaPandamonium** [comment]
> During runtime, very regularly, an error is thrown within the on_mesage_delete method.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 441, in _run_event
>     await coro(*args, **kwargs)
>   File "/ChadCounting/bot.py", line 103, in on_message_delete
>     current_user_minutes_ban = check_user_banned(user_id, guild_id)
>   File "/ChadCounting/bot.py", line 491, in check_user_banned
>     user_time_banned = guild_data[guild_id]["users"][user_id]["time_banned"]
> KeyError: 1115440368331272233
> [2024-03-12 20:39:02] [ERROR   ] discord.client: Ignoring exception in on_message_delete
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 441, in _run_event
>     await coro(*args, **kwargs)
>   File "/ChadCounting/bot.py", line 103, in on_message_delete
>     current_user_minutes_ban = check_user_banned(user_id, guild_id)
>   File "/ChadCounting/bot.py", line 491, in check_user_banned
>     user_time_banned = guild_data[guild_id]["users"][user_id]["time_banned"]
> KeyError: 538417546303373342```
> ```

You need to ensure that you check whether a user exists in guild_data before accessing their banned status to prevent the KeyError. Perhaps check your check_user_banned function.
